In [1]:
from model_On_Array2 import *
import pandas as pd
import os
import sys
import itertools
import random
from pathlib import Path
import numpy as np
import dataprocessing2
import glob
import os.path
from datetime import datetime, timedelta
import process_utils
from sklearn.metrics import mean_squared_error
from scipy.optimize import minimize
from scipy.optimize import leastsq
from scipy.optimize import least_squares
from sklearn.model_selection import train_test_split
import pickle 

In [2]:
model=mainmodel(maison='singleroom')
model.update_theta()
model.set_theta(model.theta)

In [3]:
model.setupdata()

In [4]:
model.trainarray.get('state')[0]

array([21.3125])

In [22]:
line=0
dic=model.trainarray
state=dic.get('state')
Tset=dic['Tset']
external=dic['external']
Twater=dic['Twater']
switch=dic['switch']
occupancy=dic['occupancy']
timestep=dic['timestep']


In [29]:
[model.thermalmodel(state[0]\
                  ,Tset[0]\
                  ,external[0]\
                  ,Twater[0]\
                  ,switch[0]\
                  ,occupancy[0]\
                  ,timestep[0]\
                  ,noisymeasure=False) for i in range(10)]

state [21.41153372]
state [21.4118273]
state [21.41212087]
state [21.41241445]
state [21.41270803]
state [21.4130016]
state [21.41329518]
state [21.41358876]
state [21.41388233]
state [21.41417591]


[array([21.41446948]),
 array([21.41446948]),
 array([21.41446948]),
 array([21.41446948]),
 array([21.41446948]),
 array([21.41446948]),
 array([21.41446948]),
 array([21.41446948]),
 array([21.41446948]),
 array([21.41446948])]

In [9]:
model.predict1(model.trainarray)
model.trainarray['predicted']

state [21.31338082]
state [23.1375]


array([[21.34337442],
       [23.16749306]])

In [10]:
[model.metric1(np.array([1,1,1]),dic=model.trainarray,noisymeasure=False) for i in range(5)]

state [21.34337442]
state [23.16749306]


KeyError: 'next_state'

In [7]:
[model.metric1(np.array([1,1,0.99]),dic=model.trainarray,noisymeasure=False) for i in range(5)]

[0.09360511521568249,
 0.11279616616635249,
 0.13378639866445208,
 0.1565758110907127,
 0.18116440182587074]

In [21]:
model.metric1(np.array([1,1,5]),dic=model.trainarray,noisymeasure=False)

liste à concaténer [array([1]), array([1]), array([5])]
concatenration [1 1 5]
theta avant [1 1 5]
theta après [1 1 5]
[1 1 5]
{'temperature_noise': array([0]), 'obs_noise': array([0.1]), 'Qfamily': array([0.5]), 'log_f': array([1]), 'Lambda': array([1]), 'C': array([1]), 'Prad': array([5]), 'ThetaRad1': array([5.]), 'ThetaRad2': array([1.]), 'Pocc': array([1.])}
rms 0.06428586718623445


0.06428586718623445

In [53]:
res_2 = least_squares(fun=model.res1, x0=np.array([10,10,10])\
                     ,args=(model.trainarray,False),jac='3-point'\
                     ,bounds=(np.array([0.01,0.01,0.01]),np.array([1000,1000,1000])))

In [54]:
res_2

 active_mask: array([0, 0, 0])
        cost: 169531.75467479485
         fun: array([3.2919246 , 3.25442521, 3.25442521, ..., 3.1976999 , 3.18870337,
       3.22445093])
        grad: array([2579726.46610443, 2579709.21014316, 2579723.16267978])
         jac: array([[24.71174133, 24.71157722, 24.71171204],
       [24.71183422, 24.71167011, 24.71180493],
       [24.71183422, 24.71167011, 24.71180493],
       ...,
       [24.79888377, 24.79871901, 24.79885425],
       [24.63406768, 24.6339041 , 24.63403854],
       [24.71636729, 24.71620312, 24.71633796]])
     message: '`xtol` termination condition is satisfied.'
        nfev: 12
        njev: 1
  optimality: 25771467.39638326
      status: 3
     success: True
           x: array([10., 10., 10.])

In [22]:
soln = minimize(model.metric1, model.theta, args=(model.trainarray)\
               ,options={'maxiter':200}\
               )

In [23]:
soln.x

array([1., 1., 1.])

In [ ]:
object = Object() 
filehandler = open(filename, 'w') 
pickle.dump(object, filehandler)

In [16]:
model.set_theta(soln.x)

In [17]:
model.metric1(theta=model.theta,dic=model.trainarray)

0.03827622505589799